baseURL = 'https://top-xiao.github.io/blog/'
languageCode = 'en-us'
title = "Arnold's Homepage"
theme = "PaperMod"
[module]
[[module.mounts]]
source = "content"
target = "content"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]
