baseURL = 'https://top-xiao.github.io/blog/'
languageCode = 'en-us'
title = "Arnold's Homepage"
theme = "hugo-book"
[module]
[[module.mounts]]
source = "content"
target = "content"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
